### ISSUE TITLE
Orange PI 3 support

### ISSUE THREAD

**Issue by rsglobal** [devel-opi/android_sunxi_manifest#32]
Requires:
1. https://gitlab.freedesktop.org/mesa/mesa/merge_requests/2439 - Merged (pushed)
2. https://gitlab.freedesktop.org/mesa/mesa/merge_requests/2617 - Merged
3. https://gitlab.freedesktop.org/mesa/mesa/merge_requests/2663 - Merged
4. https://lore.kernel.org/patchwork/cover/1077018/ - Pending

**Comment by AndriiZ** [comment]
I have orange pi 3 with emmc and can help with testing dev images

**Comment by StanislavGoncharovGL** [comment]
@AndriiZ,
Thank You very much, I hope in the nearest time we start to do it. Currently we have 2 boards and issue with CPU overheating. Do You use any cooling on your board?

**Comment by kondratuka7** [comment]
@StanislavGoncharovGL  I have burned armbian to opi3. Temperature was about 40C on idle and 70-80 on heavy load (7zip test), after 10 min CPU throttled. I have attached passive radiator to cpu

**Comment by StanislavGoncharovGL** [comment]
@AndriiZ, 
Throttling - it is a good feature for implementation :) Thank You...

**Comment by rsglobal** [comment]
Patches https://lore.kernel.org/patchwork/patch/1077020/ and  https://lore.kernel.org/patchwork/patch/1077021/ has been added to our kernel fork.

**Comment by rsglobal** [comment]
@StanislavGoncharovGL 

Please include latest arm64 gcc compiler from linaro into the manifest.

**Comment by rsglobal** [comment]
https://github.com/megous/linux/commits/opi3-5.4

**Comment by rsglobal** [comment]
Implemented in v0.2.0: https://github.com/GloDroid/glodroid_manifest/releases/tag/v0.2.0
