### ISSUE TITLE
Support for Orange-PI PC

### ISSUE THREAD

**Issue by StanislavGoncharovGL** [devel-opi/android_sunxi_manifest#43]
Add 250MiB ZRAM swap for boards with 1GB of RAM

**Comment by rsglobal** [comment]
Image with DTS for plus2e runs fine on OrangePI PC

**Comment by rsglobal** [comment]
Implemented in v0.2.0: https://github.com/GloDroid/glodroid_manifest/releases/tag/v0.2.0
