### ISSUE TITLE
Add/Check support of throttling

### ISSUE THREAD

**Issue by StanislavGoncharovGL** [devel-opi/android_sunxi_manifest#48]
It is very needed feature.

**Comment by rsglobal** [comment]
First of all thermal driver needs to be included into the kernel.
https://patchwork.kernel.org/cover/11088251/

IMO Helping sunxi guys with mainlining is the best option.

**Comment by rsglobal** [comment]
Support is provided in kernel v5.6 and v5.8. No additional support from userspace required.
