### ISSUE TITLE
Add Android TV variant to build

### ISSUE THREAD

**Issue by rsglobal** [devel-opi/android_sunxi_manifest#49]

**Comment by MaksymPrymierov** [comment]
I have created the pull request which added Android TV variant to build:
https://github.com/android2orangepi-dev/android_allwinner_bsp/pull/28

**Comment by hostkit** [comment]
Relase type Android tv plase.....
Ir remote working?

**Comment by rsglobal** [comment]
Implemented in v0.2.0: https://github.com/GloDroid/glodroid_manifest/releases/tag/v0.2.0
