### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by joek85** [devel-opi/android_sunxi_manifest#52]
hello,
tested this release:
https://github.com/android2orangepi-dev/android_allwinner_manifest/releases/tag/OrangePlus2e_AndroidQ_preview3

Opi Plus 2E - 2GB memory, this is my meminfo

`MemTotal:        2029220 kB
MemFree:          841600 kB
MemAvailable:    1404820 kB
Buffers:           14032 kB
Cached:           715156 kB
SwapCached:            0 kB
Active:           556212 kB
Inactive:         388432 kB
Active(anon):     327224 kB
Inactive(anon):     3364 kB
Active(file):     228988 kB
Inactive(file):   385068 kB
Unevictable:      112104 kB
Mlocked:            8952 kB
HighTotal:       1277940 kB
HighFree:         306044 kB
LowTotal:         751280 kB
LowFree:          535556 kB
SwapTotal:             0 kB
SwapFree:              0 kB
Dirty:               556 kB
Writeback:             0 kB
AnonPages:        327568 kB
Mapped:           398236 kB
Shmem:            106748 kB
KReclaimable:      22096 kB
Slab:              53068 kB
SReclaimable:      21520 kB
SUnreclaim:        31548 kB
KernelStack:        6880 kB
PageTables:        23076 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:     1014608 kB
Committed_AS:   22928560 kB
VmallocTotal:     245760 kB
VmallocUsed:        2164 kB
VmallocChunk:          0 kB
Percpu:              864 kB
CmaTotal:         131072 kB
CmaFree:          106124 kB
`

Tested with mouse, i can say it is pretty fast UI but there is also lags in drawings, like the cursor disappear when hovering over the icons and when switching activities.

**Comment by rsglobal** [comment]
@joek85 ,

Hello Joe,
Thanks for joining.

Some of UI lags are already fixed (cursor under icons issue and performance slightly improved).
Changes will be available in preview-4 soon.

**Comment by joek85** [comment]
Thank you for your effort.

**Comment by StanislavGoncharovGL** [comment]
Sorry, issue is even actual now.

**Comment by joek85** [comment]
regarding the memory usage, is it normal?does Android 10 requires that much memory to operate?

**Comment by rsglobal** [comment]
Memory consumption of Android-10 is about 4x time greater than Android-4.4.
For some reason already existed applications start to use more memory than before.
Therefore, it is very unlikely we can use 512Mb boards with Android-10.
