### ISSUE TITLE
Some question regarding the android Linux kernel version

### ISSUE THREAD

**Issue by lorn10** [devel-opi/android_sunxi_manifest#54]
Hi there!

This is not a bug report. I just want to note here that it would be great if there could be added some more detailed information regarding the used Linux kernel version in this build.

That is quite relevant because later 5.x kernel releases have brought significant Lima driver improvements. For example, the Linux Kernel 5.2 branch has introduced native Mali support:
https://www.phoronix.com/scan.php?page=news_item&px=Panfrost-DRM-For-Linux-5.2

The brand new Kernel 5.8 has furthermore improved the power management capability of several Mali GPUs:
https://www.phoronix.com/scan.php?page=news_item&px=Lima-Runtime-Power-Management

However, the highest LTS kernel versions which Android currently uses are 4.14.x and 4.19.x. So far, no 5.x kernel version is avaiable.

Were certain Kernel 5.x Lima Mali improvements back-ported to the Android kernel used in this project? Are certain portions of the Kernel 5.x Lima Mali features avaiable through an external MESA package also for older Kernel versions like 4.14.x?

Kind regards
lorn10

**Comment by StanislavGoncharovGL** [comment]
Hello. 
The next generation of the project has been moved to https://github.com/glodroid/glodroid_manifest
Please go there.
The current version is not supported

**Comment by rsglobal** [comment]
Hello @lorn10 ,

We are using latest mainline kernel.
For example GloDroid pre-release v0.2.0 uses v5.6

We are also using latest mainline mesa in this project.

**Comment by lorn10** [comment]
Hi there again!

Thanks @rsglobal for that informative replay. So it seems that you are regarding the kernel version a big step ahead of Google and most other "normal" Android AOSP based releases. Fascinating!

It is really nice to see that it is possible to build a up-to-date Android 10 with a quite modern 5.6 kernel. Maybe the GloDroid project will give other devs some motivation to use your kernel at other Mali 400 GPU based SoC like the NovaThor U8500. This would allow theoretically several older but quite popular phones like the Samsung S III mini (GT-I8190) a small rebirth.

I use currently the official AKOP Android 9 release on a Samsung S 4 mini (Snapdragon SoC). With the "low RAM" flag aka "Android Go mode" enabled it runs really awesome on that old hardware. ;-)
 
Kind regards
lorn10

**Comment by rsglobal** [comment]
We're using https://android.googlesource.com/kernel/common/+/refs/heads/android-mainline, that tracks linux kernel master with minor adjustments.
